### ISSUE TITLE
gradients as colors

### ISSUE THREAD

**Issue by mastef** [Tw1ddle/geometrize-haxe#7]
For more natural "strokes", the shapes could have gradients instead of fill colors. This would obviously increase cpu by quite a factor.

**Comment by Tw1ddle** [comment]
I think this would be complicated to implement as part of the core optimizing algorithm, because you'd want to pick the "best" gradients, which would add another layer to the optimization problem.

However, it could be done as a cheap postprocessing effect by sampling the pixels under the shapes that were picked, along with whatever other additions you could use to make a shape look like a brushlike stroke.

I'm not going to implement this as part of this project, but I might make a separate tool for postprocessing shape data/images in future.
